autoload colors
colors

[ -w /root ] && ZDOTDIR=/root
ZDOTDIR=${ZDOTDIR:-$HOME}


autoload -U compinit        # load completion system
compinit -C                 # dump compinit in .zcompdump
compinit -d $ZDOTDIR/.zcompdump

autoload -U zrecompile
[ -f ~/.zshrc ] && zrecompile -p ~/.zshrc
[ -f ~/.zshrc.zwc.old ] && rm -f ~/.zshrc.zwc.old
[ -f $ZDOTDIR/.zcompdump ] && zrecompile -p $ZDOTDIR/.zcompdump
[ -f $ZDOTDIR/.zcompdump.zwc.old ] && rm -f $ZDOTDIR/.zcompdump.zwc.old


[ -w $ZDOTDIR/.zsh_history ] && HISTFILE=$ZDOTDIR/.zsh_history    # history file
HISTSIZE=3000               # size of history
LISTMAX=1000                # never ask
NULLCMD='cat'               # use cat for > null commands
READNULLCMD=`which less more|head -1`    # use present pager for < null commands
REPORTTIME=10               # report time if execution exceeds amount of seconds
SAVEHIST=3000               # maximum of history events to be save
LOGCHECK=60
watch=(notme)               # watch login/logout
WORDCHARS="*?_-.[]~=/&;!#$%^(){}<>" # part of word in line editor

zstyle ':completion:*' add-space true
zstyle ':completion:*' completer _expand _complete _match _prefix _approximate _list
zstyle ':completion:*' menu select=1
zstyle ':completion:*' file-sort name
zstyle ':completion:*' list-colors ${(s.:.)ZLS_COLORS}
zstyle ':completion:*' matcher-list 'r:|[._-]=** r:|=**' 'l:|=** r:|=**'
zstyle ':completion:*' menu select
zstyle ':completion:*:approximate:*' max-errors 'reply=( $(( ($#PREFIX+$#SUFFIX)/3 )) numeric )'
zstyle ':completion:*:complete:*' use-cache 1
zstyle ':completion:*:complete:*' cache-path $ZDOTDIR/.zcompcache/

alias ls="ls -F --color=auto"
export EDITOR="vim"
export CVSEDITOR="vim"
export LANG="fr_FR.UTF-8"
export PAGER=less
export PROMPT="%{$fg[white]%} %D{%H:%M:%S} %{$fg[cyan]%}%n@%m %{$fg[green]%}%B%2~%b %{$reset_color%}%% "
