#!/usr/bin/php
<?
$link = mysql_connect("localhost", "squid", "squid42sh");
mysql_select_db("squid");

while (!feof(STDIN)) {
		$DST = trim(fgets(STDIN));

		$result = mysql_query("SELECT 1 FROM dst where dst like '%".$DST."'");
		
		if (mysql_num_rows($result)>0) {
       		        fwrite(STDOUT, "OK\n");
		} else {
			fwrite(STDOUT, "ERR\n");
		}
}
mysql_close($link);
?>

