syntax on
set nocompatible
set nomodeline
set nobackup     " keep a backup file
set backspace=indent,eol,start " allow backspacing over everything in insert mode
set history=500      " keep 50 lines of command line history
set ruler       " show the cursor position all the time
set showcmd        " Show (partial) command in status line.
set showmode    " Affiche "INSERT" ou "VISUAL"...
set showmatch      " Show matching brackets.
"set textwidth=72     " Don't wrap lines by default 
filetype plugin indent on
"
" When editing a file, always jump to the last known cursor position.
" Don't do it when the position is invalid or when inside an event handler
" (happens when dropping a file on gvim).
autocmd BufReadPost *
\ if line("'\"") > 0 && line("'\"") <= line("$") |
\   exe "normal g`\"" |
\ endif

